version: '2'
services:
  test_printed_v5-app:
    image: test_printed_v5
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://test_printed_v5-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=test_printed_v5
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  test_printed_v5-mongodb:
    extends:
      file: mongodb.yml
      service: test_printed_v5-mongodb
