version: '2'
services:
  test_printed_v5-mongodb:
    image: mongo:4.0.12
    ports:
      - '27017:27017'
    command: mongos --configdb test_printed_v5-mongodb-config
  test_printed_v5-mongodb-node:
    build:
      context: .
      dockerfile: mongodb/MongoDB.Dockerfile
    command: mongod --replSet rs1 --noprealloc --smallfiles
  test_printed_v5-mongodb-config:
    image: mongo:4.0.12
    container_name: test_printed_v5-mongodb-config
    command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
